In [1]:
import numpy as np

In [2]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
char_arr2=np.array(["Supervised","Unsupervised","seMi-Supervised","Reinforcement"])
low_arr=np.char.lower(char_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [6]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [7]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [9]:
arr1.dtype

dtype('int32')

In [10]:
char_arr2.dtype

dtype('<U15')

In [14]:
arr8=np.array([1,2,3,4,5],dtype='float64')
arr8

array([1., 2., 3., 4., 5.])

In [15]:
arr8.dtype

dtype('float64')

In [16]:
arr2conv=arr8.astype('f')
arr2conv

array([1., 2., 3., 4., 5.], dtype=float32)

In [17]:
arr2conv=arr8.astype('i')
arr2conv

array([1, 2, 3, 4, 5], dtype=int32)

In [18]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [19]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [20]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [21]:
ars1=np.zeros(3)
ars1

array([0., 0., 0.])

In [25]:
ars3=np.random.random(3)
ars3

array([0.25772139, 0.42661141, 0.42294789])

In [37]:
numone=np.ones((3,2))
numone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
dimones=np.ones((3,3,2))
dimones

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [43]:
dimones.ndim

3

In [48]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
addition=ar1+ar2
print("addition:\n",addition)

addition:
 [[ 6  8 10]
 [12 14 16]]


In [49]:
sub=ar1-ar2
print("sub:\n",sub)

sub:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [50]:
mul=ar1*ar2
print(mul)

[[ 5 12 21]
 [32 45 60]]


In [51]:
div=ar1/ar2
print(div)

[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [52]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


In [53]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr1d=np.array([10,20,22])

result=arr2d+arr1d
result

array([[11, 22, 25],
       [14, 25, 28]])

In [54]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr1d=np.array([10,20,22])

result=arr2d-arr1d
result

array([[ -9, -18, -19],
       [ -6, -15, -16]])

In [55]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr1d=np.array([10,20,22])

result=arr2d*arr1d
result

array([[ 10,  40,  66],
       [ 40, 100, 132]])

In [60]:
range_arr=np.arange(0,423,76)
range_arr

array([  0,  76, 152, 228, 304, 380])

In [63]:
a=np.random.randint(low=1,high=6,size=(2,3))
a

array([[3, 4, 5],
       [4, 3, 1]])

# 

In [64]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
ar2


array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [66]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [68]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [71]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [73]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3
